### ISSUE TITLE
Provide backgrounds?

### ISSUE THREAD

**Issue by mattiasJohnson** [bresilla/dotfiles_old#1]
Hi!
Your setup looks amazing! I was wondering if you could upload the backgrounds that you are using as well?

**Comment by bresilla** [comment]
_"I'm sorry Dave, I'm afraid I can't do that" - HAL 9000_


There is this guy from Czech Republic, a freelance digital artist and illustrator, and you can support him in [patreon](https://www.patreon.com/kvacm/overview) and you get 5-6 wallpapers per month.
